# Generated by Django 5.1 on 2024-08-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('post_date', models.DateField(blank=True)),
                ('blog_image', models.ImageField(upload_to='blog_images/')),
                ('blog_url', models.URLField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CertficateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institude', models.CharField(max_length=100)),
                ('certi_name', models.CharField(max_length=100)),
                ('certi_url', models.URLField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ClinetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_logo', models.ImageField(upload_to='partner_logo')),
                ('partner_url', models.URLField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Required', max_length=254)),
                ('your_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=254)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True, default='Present')),
            ],
        ),
        migrations.CreateModel(
            name='ExperineceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True, default='Present')),
                ('institude', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about_me', models.CharField(max_length=254)),
                ('job_title', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='Profile_picture')),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=254)),
                ('fb_url', models.URLField(blank=True, max_length=100)),
                ('insta_url', models.URLField(max_length=100)),
                ('x_url', models.URLField(blank=True, max_length=100)),
                ('github_url', models.URLField(blank=True, max_length=100)),
                ('linkdin_url', models.URLField(blank=True, max_length=100)),
                ('cv_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_logo', models.ImageField(upload_to='job_logo/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('WEB_DEVELOPMENT', 'Web Development'), ('MOBILE_DEVELOPMENT', 'Mobile Development'), ('DATA_SCIENCE', 'Data Science'), ('GRAPHIC_DESIGN', 'Graphic Design'), ('MARKETING', 'Marketing')], default='Web Development', max_length=100)),
                ('image', models.ImageField(upload_to='project_image/')),
                ('project_url', models.URLField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_profile', models.ImageField(upload_to='client_images/')),
                ('client_name', models.CharField(max_length=100)),
                ('client_feedback', models.TextField()),
            ],
        ),
    ]
