# Generated by Django 5.1 on 2024-08-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='updated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='whatsapp_url',
            field=models.URLField(default='https://wa.me/3174196972'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='category',
            field=models.CharField(choices=[('WEB_DEVELOPMENT', 'Web Development'), ('PYTHON_DEVELOPMENT', 'Python Development'), ('DATA_SCIENCE', 'Data Science'), ('COMPUTER_VISION', 'Computer Vison')], default='Web Development', max_length=100),
        ),
    ]
