# Generated by Django 5.1 on 2024-08-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_aboutmodel_remove_homemodel_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialsmodel',
            name='feedback_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
