# Generated by Django 5.1 on 2024-08-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_testimonialsmodel_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialsmodel',
            name='feedback_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
