# Generated by Django 5.1 on 2024-08-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_testimonialsmodel_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certficatemodel',
            name='issued_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
