# Generated by Django 5.1 on 2024-08-22 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_certficatemodel_issued_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatrgoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.catrgorymodel'),
        ),
    ]
