# Generated by Django 5.1 on 2024-08-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_catrgorymodel_alter_projectmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=254)),
                ('whatsapp_no', models.CharField(default='0317 4196972', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='my_profile')),
                ('job_title', models.CharField(max_length=100)),
                ('cv', models.FileField(blank=True, max_length=254, upload_to='my_cv')),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowContactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=254)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SocialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=254)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='cv',
            field=models.FileField(blank=True, max_length=200, upload_to='my_cv/'),
        ),
    ]
