# Generated by Django 5.1 on 2024-08-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_socialmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcontactsmodel',
            name='link',
            field=models.URLField(blank=True, default=None, max_length=254),
        ),
    ]
