# Generated by Django 5.1 on 2024-08-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_showcontactsmodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcontactsmodel',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='socialmodel',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
