# Generated by Django 5.1 on 2024-08-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_showcontactsmodel_updated_on_socialmodel_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcontactsmodel',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=254),
        ),
    ]
