# Generated by Django 5.1 on 2024-08-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_showcontactsmodel_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('cv_file', models.FileField(max_length=254, upload_to='my_cv/')),
                ('update_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HomeModel',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='cv',
        ),
    ]
