# Generated by Django 5.1 on 2024-08-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_cvmodel_delete_homemodel_remove_profilemodel_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvmodel',
            name='details',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
