# Generated by Django 5.1 on 2024-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_cvmodel_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendSkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('bootstrap', 'Bootstrap')], max_length=20)),
                ('expertise', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('level', models.PositiveIntegerField(help_text='Enter skill level as a percentage (0-100)')),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
    ]
