# Generated by Django 5.1 on 2024-08-25 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_languagemodel_alter_frontendskillmodel_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('level', models.PositiveIntegerField(help_text='Enter skill level as a percentage (0-100)')),
                ('icon', models.CharField(max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai', to='portfolio.languagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='BackendSkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('level', models.PositiveIntegerField(help_text='Enter skill level as a percentage (0-100)')),
                ('icon', models.CharField(max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backends', to='portfolio.languagemodel')),
            ],
        ),
    ]
