# Generated by Django 5.1 on 2024-08-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_aiskillmodel_backendskillmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='job_logo',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
